### ISSUE TITLE
Free money glitch

### ISSUE THREAD

**Issue by JustTalDevelops** [Leonidius20/TradingInterface#2]
Hey!
If users get, say, a diamond, which on my server is sold for quite a bit, players can rename that diamond to diamond, then sell it, and make infinite cash.
Please do resolve this issue!
Thanks!

**Comment by TalhaAzeem37** [comment]
Hello?

**Comment by DueKay** [comment]
Hallo Leonidius20,

Leider ist mein Englisch nicht so gut, aber ich schick hier drunter noch eine Englische Google Übersetzung drunter :D
Und ja! Wenn Items umbenannt oder verzaubert werden, verbleiben die Items nach dem verkauf im Inventar. Ist mir auch schon aufgefallen. Da ich aber lediglich Sachen dort zum kaufen anbiete (die User kaufen können) ist der Bug für mich nicht so relevant :D

Hätte ehrlich gesagt lieber einen begehbaren Adminshop erstellt. Aber dafür gibt es leider nur QuickShop und das ist leider nicht so konfigurierbar wie ich möchte
Hab den Owner des Plugins schon angeschrieben, aber kommt keine Rückmeldung

Lg DueKay
______________________________________________________________________

Hello Leonidius20,

Unfortunately, my English is not that good, but I'm sending an English Google translation underneath: D
And yes! When items are renamed or enchanted, items remain in inventory after sale. I noticed that too. But since I only offer things to buy there (the user can buy), the bug is not so relevant for me: D

I honestly would rather have created a walk-in adminshop. But unfortunately there is only QuickShop and that is unfortunately not as configurable as I would like
Have the owner of the plugin already written, but no feedback

Lg DueKay

**Comment by Leonidius20** [comment]
@DueKay Hello, thanks for letting me know about the issue! I already know a way to fix this, but it will take some time since I don't have much free time nowdays.

**Comment by DueKay** [comment]
No problem
And I'm glad if the problem is solvable.
For me, the problem but as I said not relevant, since I will most likely use yet another plugin for the AdminShop.
best regards
DueKay

**Comment by Leonidius20** [comment]
Must be fixed in version 2.0.0!
